name: Build
run-name: ${{ github.event_name }} by ${{ github.actor }} (${{ github.ref }})
on: [push]
jobs:
  build:

    strategy:
     matrix:
      host: ["windows-2022"]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: lukka/get-cmake@latest
      - name: Build
        run: cmake --build --preset default