name: Build
run-name: ${{ github.event_name }} by ${{ github.actor }} (${{ github.ref }})
on: [push]
jobs:
  build:

    strategy:
     matrix:
      host: ["windows-2022"]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cmake --preset ninja-multi && cmake --build out/build/ninja-multi
