name: Build
run-name: ${{ github.event_name }} by ${{ github.actor }} (${{ github.ref }})
on: [push]
jobs:
  build:
    strategy:
     matrix:
      host: ["windows-2022"]
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: d07689ef165f033de5c0710e4f67c193a85373e1
      - name: Install dependencies
        run: vcpkg install sfml spdlog
      - name: Build
        run: cmake --preset default -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake && cmake --build out/build/default
