name: Build
run-name: ${{ github.event_name }} by ${{ github.actor }} (${{ github.ref }})
on: [push]
env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
jobs:
  build:
    strategy:
     matrix:
      host: ["windows-2022"]
    runs-on: ${{ matrix.host }}
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - uses: actions/checkout@v4
      - name: Install SFML
        run: vcpkg install sfml --head
      - name: Install spdlog
        run: vcpkg install spdlog
      - name: Build
        run: cmake --preset default -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_REQUIRE_FIND_PACKAGE_sfml=YES -DCMAKE_REQUIRE_FIND_PACKAGE_spdlog=YES -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" && cmake --build out/build/default
